---
driver:
  name: vagrant
  require_chef_omnibus: 12.21.3

provisioner:
  name: policyfile_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: centos-6.8
- name: centos-7.3
- name: ubuntu-14.04
- name: ubuntu-16.04

suites:
- name: default
